{
    'name': 'Egp hr',
    'version': '1.0',
    'summary': 'MCIT-Afghanistan ERP HR module streamlines HR processes',
    'description': 'MCIT-Afghanistan HRMIS',
    'category': 'Custom',
    'sequence': -3,
    'author': 'Faridullah Qaderi',
    'website': 'https://mcit.gov.af/',
    'depends': ['hr', 'mail', 'base', 'hr_recruitment'],
    'data': [
        'security/egp_hr_security.xml',
        'security/ir.model.access.csv',
        'views/egp_hr_department_view.xml',
        'views/egp_hr_job_view.xml',
        'views/egp_hr_work_location_view.xml',
        'views/egp_hr_position_rank_view.xml',
        'views/egp_hr_position_status_view.xml',
        # 'views/egp_hr_job_kanban_view.xml',
        'data/egp_hr_res_partner_default_data.xml',
        'data/egp_hr_work_location_default_data.xml',
        'data/egp_hr_position_status_default_data.xml',
        'data/egp_hr_contract_type_default_data.xml',
        'data/egp_hr_position_rank_default_data.xml',
        'data/egp_hr_department_default_data.xml',
        'data/egp_hr_job_default_data.xml',
        'report/job_summary_paper_format.xml',
        'report/job_summary_report.xml',
    ],
    'demo': [
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
